// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcGhq-Wt0ID13fs6VO_bduByqMGr49fJM',
    appId: '1:782565217206:android:1aadf23dc732c581fda717',
    messagingSenderId: '782565217206',
    projectId: 'fooddelivery-f3e0c',
    storageBucket: 'fooddelivery-f3e0c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhN3XUEwFypstFJwMHN5oVwVonNw6oLYM',
    appId: '1:782565217206:ios:10175d5576edfff9fda717',
    messagingSenderId: '782565217206',
    projectId: 'fooddelivery-f3e0c',
    storageBucket: 'fooddelivery-f3e0c.appspot.com',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjkD2c4LlEYh3YfyiRH5GG1NSYcQ7iSOU',
    appId: '1:782565217206:web:358f643f3c5d7845fda717',
    messagingSenderId: '782565217206',
    projectId: 'fooddelivery-f3e0c',
    authDomain: 'fooddelivery-f3e0c.firebaseapp.com',
    storageBucket: 'fooddelivery-f3e0c.appspot.com',
    measurementId: 'G-96Q1EY8W57',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhN3XUEwFypstFJwMHN5oVwVonNw6oLYM',
    appId: '1:782565217206:ios:10175d5576edfff9fda717',
    messagingSenderId: '782565217206',
    projectId: 'fooddelivery-f3e0c',
    storageBucket: 'fooddelivery-f3e0c.appspot.com',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjkD2c4LlEYh3YfyiRH5GG1NSYcQ7iSOU',
    appId: '1:782565217206:web:0743580a8311132dfda717',
    messagingSenderId: '782565217206',
    projectId: 'fooddelivery-f3e0c',
    authDomain: 'fooddelivery-f3e0c.firebaseapp.com',
    storageBucket: 'fooddelivery-f3e0c.appspot.com',
    measurementId: 'G-ZRKXFHHTLT',
  );

}